### ISSUE TITLE
Accordion UI Bug - Premature "Quest Completed Successfully" Toaster Display

### ISSUE THREAD

**Issue by EvolOfThings** [talentprotocol/web-dapp#1773]
### Bug Description:
On the home page of Talent Protocol, there is an issue with the accordion UI container that contains quest cards, specifically the **Christmas Special Quests** container box. When a user clicks on an incomplete quest item within this container, the toaster displays the message **"Quest Completed Successfully"** even before the quest has been completed.

### Steps to Reproduce:
1. Navigate to the home page of Talent Protocol.
2. Locate and click on any incomplete quest items displayed in the **Christmas Special Quests** container box.
3. Observe the toaster that appears to the top right of the screen, displaying the message **"Quest Completed Successfully"**.

### Expected Behavior:
The toaster message should only appear after the quest has been successfully completed, not prematurely upon clicking an incomplete quest item.

**Screenshot:**
<img width="1201" alt="Screenshot 2023-12-16 at 7 53 06 PM" src="https://github.com/talentprotocol/web-dapp/assets/12666706/70ddfbe8-a89c-4d34-9533-8544b8c97f2f">

**Comment by EvolOfThings** [comment]
I'm eager to contribute to resolving this bug, please let me know if I could pick this up. @francisco-leal @RubenSousaDinis @verdefred

**Comment by francisco-leal** [comment]
hey @EvolOfThings, feel free to make the change if you want, we have a tech onboarding document here: https://talentprotocol.notion.site/Tech-Onboarding-778921844c884f93a05a55aa9f69e6fb?pvs=4

**Comment by EvolOfThings** [comment]
I will work on it. Thank you @francisco-leal

**Comment by EvolOfThings** [comment]
losing this issue, the feature has been depreciated.
