### ISSUE TITLE
Bug: Dropdown Notification Crashes the App

### ISSUE THREAD

**Issue by EvolOfThings** [talentprotocol/web-dapp#1873]
**Bug Description:** Upon triggering the notification dropdown, an issue arises when attempting to load more after the first attempt, leading to a complete app crash. The entire navigation bar disappears, forcing users to perform a hard refresh of the entire page.

<img width="1498" alt="Screenshot 2024-01-31 at 6 24 38 PM" src="https://github.com/talentprotocol/web-dapp/assets/12666706/c5b87dd4-96fc-4e6b-80aa-eb557d32022c">

Additionally, the second API call (`api/v1/notifications?page=3`) returns an **error code 500.** 
This occurs despite the first API call (`api/v1/notifications?page=2`) successfully providing pagination data as follows: 
```pagination: {currentPage: 2, lastPage: 19}```

<img width="1500" alt="Screenshot 2024-01-31 at 6 22 48 PM" src="https://github.com/talentprotocol/web-dapp/assets/12666706/baeaee9c-ac05-4183-9dba-8d2650356958">

@francisco-leal

**Comment by RubenSousaDinis** [comment]
Hi! Thanks for submitting the issue!

We've provided a fix for it here: #1875
